= KubeVirt Objects
ifdef::backend-pdf[]
:doctype: book
:compat-mode!:
:pagenums: :pygments-style: bw :source-highlighter: pygments
:experimental:
:specialnumbered!:
:chapter-label:
endif::[]
:imagesdir: images
:numbered:
:toc:
:toc-placement: preamble
:icons: font
:toclevels: 3
:showtitle:

{empty}

= Introduction

The https://github.com/kubevirt/kubevirt/[KubeVirt] project provides extensions to Kubernetes via
https://kubernetes.io/docs/concepts/api-extension/custom-resources/[custom resources].
These resources are a collection a API objects that defines a virtual machine within Kubernetes.
Let's take a look at the objects that are available.

== KubeVirt top-level objects

Below is a list of the top level API objects and descriptions that KubeVirt provides.

- VirtualMachine (vm[s]) - represents a virtual machine in the runtime
  environment of Kubernetes.
- OfflineVirtualMachine (ovm[s]) - handles the virtual machines that are not running or are in a stopped state.
- VirtualMachinePreset (vmpreset[s]) - is an extension to general VirtualMachine configuration behaving much like
  PodPresets from Kubernetes. When a VirtualMachine is created, any applicable VirtualMachinePresets
  will be applied to the existing spec for the VirtualMachine. This allows for re-use of common
  settings that should apply to multiple VirtualMachines.
- VirtualMachineReplicaSet (vmrs[s]) - tries to ensures that a specified number of VirtualMachine replicas
  are running at any time.

There are other top-level objects which are lists of the above four: VirtualMachineList,
OfflineVirtualMachineList, VirtualMachineReplicaSetList and VirtualMachinePresetList.

http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_domainspec[DomainSpec] is listed
as a top-level object but is only used within all of the objects above. Currently the `DomainSpec` is a
subset of what is configurable via https://libvirt.org/formatdomain.html[libvirt domain XML].

=== VirtualMachine

First let's use `kubectl` to retrieve a list of `VirtualMachine` objects.
[source,bash]
----
$ kubectl get vms -n nodejs-ex
NAME      AGE
mongodb   5d
nodejs    5d
----

Just in case if you want to return the yaml definition of a `VirtualMachine` object here
is an example.

[source,bash]
----
$ kubectl -o yaml get vms mongodb -n nodejs-ex
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
...output...
----

The first object we will annotate is `VirtualMachine`.
The important sections `.spec` for `VirtualMachineSpec` and `.spec.domain` for
`DomainSpec` will be annotated only in this section then referred to in the
other object sections.

[source,yaml]
----
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  annotations: {}
  labels: {}
  name: string
  namespace: string
----


==== Node Placement

Constrain a virtual machine to run on a node defined by matching expressions using node labels.

[source,yaml]
----
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: string
            operator: string
            values:
            - string
        weight: 0
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: string
            operator: string
            values:
            - string
----
The links below in Reference provides an example of how to use `.spec.affinity`.

===== References

- https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_nodeaffinity
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/assigning-vms-to-nodes?id=affinity-and-anti-affinity


Constrain a virtual machine to run on a node defined by node's label and value.

[source,yaml]
----
  nodeSelector: {}
----

Below is a basic example of the `nodeSelector`.
[source,yaml]
----
  nodeSelector:
    kubernetes.io/hostname: kn1.virtomation.com
----

===== References

- https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/assigning-vms-to-nodes?id=nodeselector

==== .spec.terminationGracePeriodSeconds

The length of time in seconds that after the virtual machine has been signaled to
stop will be force terminated.

[source,yaml]
----
  terminationGracePeriodSeconds: 0
----

===== References
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_virtualmachinespec

==== .spec.domain
This is of type `DomainSpec` and is the virtual machine hardware configuration.
It defines the cpu quantity, ram and cpu requests, QEMU machine type, firmware, and disks.

[source,yaml]
----
  domain:
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_domainspec

==== .spec.domain.clock

Configures the virtualize hardware clock provided by QEMU.

[source,yaml]
----
    clock:
      timezone: string
      utc:
        offsetSeconds: 0
----

===== References

- https://libvirt.org/formatdomain.html#elementsTime
- https://qemu.weilnetz.de/doc/qemu-doc.html#Debug_002fExpert-options
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_clock
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=clock

==== Clocks and Timers

Type and policy attribute that determines what action is take when QEMU misses a
deadline for injecting a tick to the guest.

[source,yaml]
----
    clock:
      timer:
        hpet:
          present: true
          tickPolicy: string
        hyperv:
          present: true
        kvm:
          present: true
        pit:
          present: true
          tickPolicy: string
        rtc:
          present: true
          tickPolicy: string
          track: string
----

===== References

- https://libvirt.org/formatdomain.html#elementsTime
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_timer
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=timers


==== CPU and Memory

The number of CPU cores a virtual machine will be assigned.
The value below will not be used for scheduling use
`.spec.domain.resources.requests.cpu` instead.

[source,yaml]
----
    cpu:
      cores: 1
----

===== References

- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=cpu
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_cpu


There are two supported resource limits and requests: `cpu` and `memory`.
A `.spec.domain.resources.requests.memory` should be defined to determine
the allocation of memory provided to the virtual machine.  These values
will be used to in scheduling decisions.

[source,yaml]
----
    resources:
      limits: {}
      requests: {}
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_resourcerequirements
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=resources-requests-and-limits
- https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-types


==== Disks

Configures a type of disk to the virtual machine and assigns a specific volume
and its type to that disk via the `volumeName`.

[source,yaml]
----
    devices:
      disks:
      - cdrom:
          bus: string
          readonly: true
          tray: string
        disk:
          bus: string
          readonly: true
        floppy:
          readonly: true
          tray: string
        lun:
          bus: string
          readonly: true
        name: string
        volumeName: string
----

===== References

- https://libvirt.org/formatdomain.html#elementsDisks
- https://qemu.weilnetz.de/doc/qemu-doc.html#Block-device-options
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/disks-and-volumes
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_disk


==== Watchdog Devices

Automaticaly trigger some action when the virtual machine operating system hangs
or crashes.

[source,yaml]
----
      watchdog:
        i6300esb:
          action: string
        name: string
----

===== References

- https://libvirt.org/formatdomain.html#elementsWatchdog
- https://qemu.weilnetz.de/doc/qemu-doc.html#Debug_002fExpert-options
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_watchdog

==== Features

After reviewing both Linux and Microsoft QEMU virtual machines managed by Libvirt
both `acpi` and `apic` are enabled.
The `hyperv` features should be enabled only for Windows-based virtual machines.

[source,yaml]
----
    features:
      acpi:
        enabled: true
      apic:
        enabled: true
        endOfInterrupt: true
      hyperv:
        relaxed:
          enabled: true
        reset:
          enabled: true
        runtime:
          enabled: true
        spinlocks:
          enabled: true
          spinlocks: 0
        synic:
          enabled: true
        synictimer:
          enabled: true
        vapic:
          enabled: true
        vendorid:
          enabled: true
          vendorid: string
        vpindex:
          enabled: true
----

===== References

- https://libvirt.org/formatdomain.html#elementsFeatures
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_features
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_featureapic
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=features
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_featurehyperv


==== QEMU Machine Type

The machine type is the emulated machine architecture provided by QEMU.

[source,yaml]
----
    machine:
      type: string
----

Here is an example how to retrieve the supported QEMU machine types.

[source,bash]
----
$ qemu-system-x86_64 --machine help
Supported machines are:
...output...
pc                   Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-2.10)
pc-i440fx-2.10       Standard PC (i440FX + PIIX, 1996) (default)
...output...
q35                  Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-2.10)
pc-q35-2.10          Standard PC (Q35 + ICH9, 2009)
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_machine
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=machine-type
- https://qemu.weilnetz.de/doc/qemu-doc.html#Standard-options

==== cloudInitNoCloud Volume

`cloudInitNoCloud` injects scripts and configuration into a virtual machine operating system.
There are three different parameters that can be used to provide
the cloud-init coniguration: `secretRef`, `userData` or `userDataBase64`.

[source,yaml]
----
  volumes:
  - cloudInitNoCloud:
      secretRef:
        name: string
      userData: string
      userDataBase64: string
----

See the link below in References for an example of how to use
`.spec.volumes.cloudInitNoCloud`.

===== References

- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/startup-scripts?id=cloud-init-examples
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_cloudinitnocloudsource

==== emptyDisk Volume

An extra qcow2 disk that is created with the virtual machine.  It will
be removed if the `VirtualMachine` object is deleted.

[source,yaml]
----
    emptyDisk:
      capacity: string
----

===== References

- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/disks-and-volumes?id=emptydisk
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_emptydisksource

==== ephemeral Volume

Temporary local copy on write image storage that will be discarded when the
`VirtualMachine` is removed.

[source,yaml]
----
    ephemeral:
      persistentVolumeClaim:
        claimName: string
        readOnly: true
    name: string
----

===== References

- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/disks-and-volumes?id=ephemeral
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_ephemeralvolumesource

==== persistentVolumeClaim Volume

For a persistent virtual machine this type of volume should be used. This
volume type persists after the `VirtualMachine` is deleted.

[source,yaml]
----
    persistentVolumeClaim:
      claimName: string
      readOnly: true
----

===== References

- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/disks-and-volumes?id=persistentvolumeclaim
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_persistentvolumeclaimvolumesource

==== registryDisk Volume

This volume type uses a virtual machine disk that is stored in a container image registry.

[source,yaml]
----
    registryDisk:
      image: string
      imagePullSecret: string
----

===== References

- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/disks-and-volumes?id=registrydisk
- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_registrydisksource


==== Virtual Machine Status

Once the `VirtualMachine` object has been created the
http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_virtualmachinestatus[VirtualMachineStatus]
will be available.  `VirtualMachineStatus` can be used in automation tools such as Ansible to
confirm running state, determine where a `VirtualMachine` is running via `nodeName` or the `ipAddress`
of the virtual machine operating system.

[source,bash]
----
kubectl -o yaml get vm mongodb -n nodejs-ex
----
[source,yaml]
----
# ...output...
status:
  interfaces:
  - ipAddress: 10.244.2.7
  nodeName: kn2.virtomation.com
  phase: Running
----

Example using `--template` to retrieve the `.status.phase` of the `VirtualMachine`.
[source,bash]
----
kubectl get vm mongodb --template {{.status.phase}} -n nodejs-ex
Running
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_virtualmachinestatus

==== Examples

- https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vm-fedora.yaml
- https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vm-windows.yaml


=== OfflineVirtualMachine

After reviewing KubeVirt objects I think that `OfflineVirtualMachine` should be used
in most use-cases. It seems more persistent than the ephemeral nature
of the `VirtualMachine` object. We will see in the annotation section that
virtual machine power state can be easily controlled by changing `running` boolean value.

Just like `VirtualMachine` we can retrieve the `OfflineVirtualMachine` objects.

[source,bash]
----
$ kubectl get ovms -n nodejs-ex
NAME      AGE
mongodb   5d
nodejs    5d
----

And display the object in yaml.
[source,bash]
----
$ kubectl -o yaml get ovms mongodb -n nodejs-ex
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
...output...
----

We continue by annotating `OfflineVirtualMachine` object.

[source,yaml]
----
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  annotations: {}
  labels: {}
  name: string
  namespace: string
spec:
----

==== Running

Running controls whether the associatied VirtualMachine is created or not.
In other words this changes the power status of the virtual machine.

[source,yaml]
----
  running: true
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_offlinevirtualmachinespec
- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/life-cycle?id=stopping-a-virtual-machine

This will create a `VirtualMachine` object which will instantiate and power
on a virtual machine.

[source,bash]
----
kubectl patch offlinevirtualmachine mongodb --type merge -p '{"spec":{"running":true }}' -n nodejs-ex
----

This will delete the `VirtualMachine` object which will power off the virtual machine.

[source,bash]
----
kubectl patch offlinevirtualmachine mongodb --type merge -p '{"spec":{"running":false }}' -n nodejs-ex
----

==== Virtual Machine Template Spec

The `VMTemplateSpec` is the definition of a `VirtualMachine` object that will
be created when `running` is set to true.

See `VirtualMachine` section `.spec` for more details about this object.

[source,yaml]
----
  template:
    metadata:
      annotations: {}
      labels: {}
      name: string
      namespace: string
    spec:
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_vmtemplatespec

==== Offline Virtual Machine Status

Once the `OfflineVirtualMachine` object has been created the
http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_offlinevirtualmachinestatus[OfflineVirtualMachineStatus]
will be available. Like `VirtualMachineStatus` `OfflineVirtualMachineStatus` can be used for automation
tools such as Ansible.

[source,bash]
----
kubectl -o yaml get ovms mongodb -n nodejs-ex
----

[source,yaml]
----
# ...output...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-04-18T19:52:18Z
    message: Created by OVM mongodb
    reason: Created by OVM mongodb
    status: "True"
    type: Running
----

Example using `--template` to retrieve the `.status.conditions[0].type` of `OfflineVirtualMachine`.

[source,bash]
----
kubectl get ovm mongodb --template "{{(index .status.conditions 0).type}}" -n nodejs-ex
Running
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_offlinevirtualmachinestatus

==== Examples

- https://github.com/kubevirt/demo/blob/master/manifests/vm.yaml

=== VirtualMachineReplicaSet

http://www.kubevirt.io/user-guide/#/workloads/controllers/virtual-machine-replica-set[VirtualMachineReplicaSet]
is great when you want to run multiple identical virtual machines.

Just like the other top-level objects we can retrieve `VirtualMachineReplicaSet`.

[source,bash]
----
$ kubectl get vmrs -n nodejs-ex
NAME      AGE
replica   1m
----

With the `replicas` parameter set to `2` the command below displays the two `VirtualMachine` objects
that were created.

[source,bash]
----
$ kubectl get vms -n nodejs-ex
NAME           AGE
replicanmgjl   7m
replicarjhdz   7m
----

Below is the subset annotation of the `VirtualMachineReplicaSet` object.

[source,yaml]
----
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineReplicaSet
metadata:
  annotations: {}
  labels: {}
  name: string
  namespace: string
spec:
----

==== Pause Rollout

This parameter if true pauses the deployment of the `VirtualMachineReplicaSet`.

[source,yaml]
----
  paused: true
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_vmreplicasetspec

==== Replica quantity

The number of `VirtualMachine` objects that should be created.

[source,yaml]
----
  replicas: 0
----

===== References

- http://www.kubevirt.io/user-guide/#/workloads/controllers/virtual-machine-replica-set?id=how-to-use-a-virtualmachinereplicaset


The selector must be defined and match labels defined in the template.
It is used by the controller to keep track of managed virtual machines.

[source,yaml]
----
  selector:
    matchExpressions:
    - key: string
      operator: string
      values:
      - string
    matchLabels: {}
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_labelselector

==== Virtual Machine Template Spec

The `VMTemplateSpec` is the definition of a `VirtualMachine` objects that will
be created.

In the `VirtualMachine` section the `.spec` `VirtualMachineSpec` describes the available parameters for that object.

[source,yaml]
----
  template:
    metadata:
      annotations: {}
      labels: {}
      name: string
      namespace: string
    spec: {}
----

===== References

- http://www.kubevirt.io/user-guide/#/workloads/controllers/virtual-machine-replica-set?id=how-to-use-a-virtualmachinereplicaset

==== Replica Status

Like the other objects we already have discussed http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_vmreplicasetstatus[VMReplicaSetStatus]
is an important object to use for automation.

[source,yaml]
----
status:
  readyReplicas: 0
  replicas: 0
----

Example using `--template` to retrieve the `.status.readyReplicas` and
`.status.replicas` of `VirtualMachineReplicaSet`.

[source,bash]
----
$ kubectl get vmrs replica --template "{{.status.readyReplicas}}" -n nodejs-ex
2
$ kubectl get vmrs replica --template "{{.status.replicas}}" -n nodejs-ex
2
----

===== References

- http://www.kubevirt.io/api-reference/v0.4.1/definitions.html#_v1_vmreplicasetstatus

==== Examples

- https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vm-replicaset-cirros.yaml

=== VirtualMachinePreset

This is used to define a `DomainSpec` that can be used for multiple virtual machines.

To configure a `DomainSpec` for multiple `VirtualMachine` objects the `selector` defines which `VirtualMachine`
the `VirtualMachinePreset` should be applied to.

[source,bash]
----
$ kubectl get vmpreset -n nodejs-ex
NAME       AGE
m1.small   17s
----

[source,yaml]
----
apiVersion: string
kind: string
metadata:
  annotations: {}
  labels: {}
  name: string
  namespace: string
----

==== Domain Spec

See the `VirtualMachine` section above for annotated details of the `DomainSpec` object.

[source,yaml]
----
spec:
  domain: {}
----

==== Preset Selector

The `selector` is optional but if not defined will be applied to all `VirtualMachine` objects -
which is probably not the intended purpose.

[source,yaml]
----
  selector:
    matchExpressions:
    - key: string
      operator: string
      values:
      - string
    matchLabels: {}
----

===== References

- http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/presets?id=virtalmachine-selector

==== Examples

- https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vm-preset-small.yaml

= Final Thoughts

We provided an annotated view into the KubeVirt objects - VirtualMachine,
OfflineVirtualMachine, VirtualMachineReplicaSet and VirtualMachienPreset.
Hopefully this will help a user of KubeVirt to understand the options
and parameters that are currently available when creating a virtual machine
on Kubernetes.

